require("options")
require("keymaps")
require("plugin-include")
require("nvim-tree-config")
require("themes.nightfox")
require("autopair-config")
require("bufferline-config")
require("lualine-config")
require("comment-config")
require("treesitter-config")
require("telescope-config")
require("alpha-config")
require("indent-config")
require("project-config")
require("lsp-config.language-servers")
require("lsp-config.lspsaga")
require("lsp-config.completion")
require("gitsigns-config")
require("toggleterm-config")
require("which-key-config")
-- require("lsp-config.null-ls")
require('better_escape-config')
-- require('goto_preview-config')
-- require('navigator-config')
require('hlslen-config')
require('hop-config')
require('nvim-gps-config')
